name: Auto CI Test On Github Actions 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install codecov pylint autopep8
          python -m pip install -r requirements.txt
          
      - name: Pre Format Code Style With Autopep8 
        run: |
          python -m autopep8 -v -i -r ./
          
      - name: Check Code Style With Pylint
        run: |
          #python -m pylint -v ./*.py
          #python -m pylint -v ./src/*.py 
          #python -m pylint -v ./test/*.py
        
      - name: Test With Demo Files
        run: |
          python setup.py install
          cd test
          python ./test.py
      
      - name: Test Code Covrage
        run: |
          export CODECOV_TOKEN="e00c5f99-4f96-4cae-9bbc-d77668302050"
          cd test
          coverage run ./test.py
          codecov
          
      - name: Auto Deploy .whl File to PyPi
        run: |
          echo -e "[ INFO ] This Funcation Under Developing will coming soon"
      
      - name: Auto Freeze a Github Release
        run: |
          echo -e "[ INFO ] This Funcation Under Developing will coming soon"
            
